import { CONSTRAINT } from '../../types/loom';

export const VIOLATION_PHRASES = [
  'no win no fee',
  'no fee guarantee',
  'no fees unless we win',
  'no fees unless they win',
  'don’t get paid unless we win',
  'don’t get paid unless they win',
  'you don’t pay unless we win',
  'you don’t pay unless they win',
  'at no cost',
  'free consultation',
  'free case evaluation',
  'free claim review',
  'cover all costs',
  'without risk',
  'risk free',
  'upfront fee',
  'out of pocket',
  'specialize',
  'specializing',
  'specialist',
  'expert',
  'expertise',
  'ensure',
  'ensuring',
  'make sure',
  'made sure',
  'guarantee',
  'maximize',
  'maximizing',
  'maximum',
  'best',
  'top',
  'top rated',
  '#1',
  'number one',
  'award',
  'award winning',
  'record breaking',
  'record setting',
  'most experienced',
  'most trusted',
  'most successful',
  'most aggressive',
  'most qualified',
  'most knowledgeable',
  'leading',
  'million',
  'multi-million',
  'settlement amount',
  'verdict amount',
  'jury award',
  'jury verdict',
  '750 million',
  '98% success rate',
  'proven track record',
  'proven result',
  'proven record of success',
  'trusted',
  'trusted by thousands',
  'trusted firm',
  'trusted legal team',
  'trusted in the community',
  'respected',
  'trusted attorney',
  'peace of mind',
  'rest assured',
  'you can trust us',
  'you’re in good hands',
  'clients rely on us',
  'give you the best chance',
  'give you an advantage',
  'we win',
  'we consistently win',
  'you’ll get justice',
  'you will win',
  'we always win',
  'always get results',
  'we win because we care',
  'winning is our goal',
  'your case is in good hands',
  'your case is our priority',
  'you deserve justice',
  'you deserve compensation',
  'guaranteed representation',
  'your recovery is our mission',
  'your victory is our goal',
  'our passion is your justice',
  'justice guaranteed',
  'fierce advocacy',
  'relentless representation',
  'aggressive representation',
  'relentless',
  'seasoned attorney',
  'deep experience',
  'thousands helped',
  'helping thousands',
  'thousands of cases won',
  'best bet',
  'stronger strategy',
  'we’re the right choice',
  'results that speak for itself',
  'results speak louder than words',
  'let’s win together',
  'justice that works',
  'justice that delivers',
  'call today for a free consultation',
  'get started today',
  'get started on your case',
];

export const TITLE_CONSTRAINTS: CONSTRAINT = {
  WARNING: 250,
  PERFECT: 350,
  MAX: 510,
};

export const DESC_CONSTRAINTS: CONSTRAINT = {
  WARNING: 530,
  PERFECT: 1060,
  MAX: 1360,
};

export const EDITOR_MIN_HEIGHT = 450;

export const otherKeywords = [
  {
    category: 'Secondary Keywords',
    keywords: ['I need a personal injury lawyer', 'free accident lawyer advice'],
  },

  {
    category: 'Check for Personal Injury KW',
    keywords: ['injury ESQ near me', 'personal injury law ESQ'],
  },
  {
    category: 'Check For Car Accident KW',
    keywords: ['car accident law firm near me', 'car accident ESQ near me'],
  },
  {
    category: 'Check For Truck Accident KW',
    keywords: ['truck accident ESQ near me'],
  },
  { category: 'Check For Uber Accident KW', keywords: ['uber injury ESQ'] },
];
