const {
  VITE_NODE_ENV,
  VITE_LOCAL_AI_ASSISTANT_DOC_INFO_API_URL,
  VITE_PROD_AI_ASSISTANT_DOC_INFO_API_URL,
  VITE_LOCAL_AI_ASSISTANT_GET_SHEET_NAMES_API_URL,
  VITE_PROD_AI_ASSISTANT_GET_SHEET_NAMES_API_URL,
  VITE_LOCAL_AI_ASSISTANT_PROCESS_SHEET_API_URL,
  VITE_PROD_AI_ASSISTANT_PROCESS_SHEET_API_URL,
  VITE_LOCAL_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL,
  VITE_PROD_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL,
  VITE_LOCAL_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL,
  VITE_PROD_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL,
  VITE_LOCAL_AI_ASSISTANT_GET_VALID_ROWS_API_URL,
  VITE_PROD_AI_ASSISTANT_GET_VALID_ROWS_API_URL,
} = import.meta.env;

export const AI_GET_DOC_INFO_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_DOC_INFO_API_URL
    : VITE_LOCAL_AI_ASSISTANT_DOC_INFO_API_URL;

export const AI_GET_SHEET_NAMES_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_GET_SHEET_NAMES_API_URL
    : VITE_LOCAL_AI_ASSISTANT_GET_SHEET_NAMES_API_URL;

export const AI_PROCESS_SHEET_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_PROCESS_SHEET_API_URL
    : VITE_LOCAL_AI_ASSISTANT_PROCESS_SHEET_API_URL;

export const AI_PROCESS_DOCUMENT_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL
    : VITE_LOCAL_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL;

export const AI_PARSE_ANALYSIS_TO_TEXT_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL
    : VITE_LOCAL_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL;

export const AI_GET_VALID_ROWS_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_GET_VALID_ROWS_API_URL
    : VITE_LOCAL_AI_ASSISTANT_GET_VALID_ROWS_API_URL;
