const {
  VITE_NODE_ENV,
  VITE_LOCAL_AI_ASSISTANT_DOC_INFO_API_URL,
  VITE_PROD_AI_ASSISTANT_DOC_INFO_API_URL,
  VITE_LOCAL_AI_ASSISTANT_GET_SHEET_NAMES_API_URL,
  VITE_PROD_AI_ASSISTANT_GET_SHEET_NAMES_API_URL,
  VITE_LOCAL_AI_ASSISTANT_PROCESS_SHEET_API_URL,
  VITE_PROD_AI_ASSISTANT_PROCESS_SHEET_API_URL,
  VITE_LOCAL_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL,
  VITE_PROD_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL,
  VITE_LOCAL_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL,
  VITE_PROD_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL,
  VITE_LOCAL_AI_ASSISTANT_GET_VALID_ROWS_API_URL,
  VITE_PROD_AI_ASSISTANT_GET_VALID_ROWS_API_URL,
  VITE_PROD_AI_CHAIN_ASSISTANT_API_URL,
  VITE_LOCAL_AI_CHAIN_ASSISTANT_API_URL,
  VITE_LOCAL_AI_ASSISTANT_FORMATTER_API_URL,
  VITE_PROD_AI_ASSISTANT_FORMATTER_API_URL,
  VITE_LOCAL_AI_CHAIN_ASSISTANT_BATCH_API_URL,
  VITE_PROD_AI_CHAIN_ASSISTANT_BATCH_API_URL,
  VITE_VIDEO_URL,
  VITE_LOCAL_AI_SYSTEM_PROMPTS_API_URL,
  VITE_PROD_AI_SYSTEM_PROMPTS_API_URL,
} = import.meta.env;

export const VIDEO_URL = VITE_VIDEO_URL;

export const AI_GET_DOC_INFO_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_DOC_INFO_API_URL
    : VITE_LOCAL_AI_ASSISTANT_DOC_INFO_API_URL;

export const AI_GET_SHEET_NAMES_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_GET_SHEET_NAMES_API_URL
    : VITE_LOCAL_AI_ASSISTANT_GET_SHEET_NAMES_API_URL;

export const AI_PROCESS_SHEET_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_PROCESS_SHEET_API_URL
    : VITE_LOCAL_AI_ASSISTANT_PROCESS_SHEET_API_URL;

export const AI_PROCESS_SHEET_MULTIPLE_ASSISTANT_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_CHAIN_ASSISTANT_BATCH_API_URL
    : VITE_LOCAL_AI_CHAIN_ASSISTANT_BATCH_API_URL;

export const AI_PROCESS_DOCUMENT_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL
    : VITE_LOCAL_AI_ASSISTANT_PROCESS_DOCUMENT_API_URL;

export const AI_PARSE_ANALYSIS_TO_TEXT_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL
    : VITE_LOCAL_AI_ASSISTANT_PARSE_ANALYSIS_TO_TEXT_API_URL;

export const AI_GET_VALID_ROWS_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_GET_VALID_ROWS_API_URL
    : VITE_LOCAL_AI_ASSISTANT_GET_VALID_ROWS_API_URL;

export const AI_MULTIPLE_ASSISTANT_API_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_CHAIN_ASSISTANT_API_URL
    : VITE_LOCAL_AI_CHAIN_ASSISTANT_API_URL;

export const AI_ASSISTANT_FORMATTER =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_ASSISTANT_FORMATTER_API_URL
    : VITE_LOCAL_AI_ASSISTANT_FORMATTER_API_URL;

export const AI_ASSISTANT_SYSTEM_PROMPTS_URL =
  VITE_NODE_ENV === 'production'
    ? VITE_PROD_AI_SYSTEM_PROMPTS_API_URL
    : VITE_LOCAL_AI_SYSTEM_PROMPTS_API_URL;
